# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hfc/protos/peer/admin.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hfc.protos.common import common_pb2 as hfc_dot_protos_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhfc/protos/peer/admin.proto\x12\x06protos\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ehfc/protos/common/common.proto\"\x9a\x01\n\x0cServerStatus\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.protos.ServerStatus.StatusCode\"Y\n\nStatusCode\x12\r\n\tUNDEFINED\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\x0b\n\x07STOPPED\x10\x02\x12\n\n\x06PAUSED\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x05\"8\n\x0fLogLevelRequest\x12\x12\n\nlog_module\x18\x01 \x01(\t\x12\x11\n\tlog_level\x18\x02 \x01(\t\"9\n\x10LogLevelResponse\x12\x12\n\nlog_module\x18\x01 \x01(\t\x12\x11\n\tlog_level\x18\x02 \x01(\t\"\"\n\x0eLogSpecRequest\x12\x10\n\x08log_spec\x18\x01 \x01(\t\"2\n\x0fLogSpecResponse\x12\x10\n\x08log_spec\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"t\n\x0e\x41\x64minOperation\x12)\n\x06logReq\x18\x01 \x01(\x0b\x32\x17.protos.LogLevelRequestH\x00\x12,\n\nlogSpecReq\x18\x02 \x01(\x0b\x32\x16.protos.LogSpecRequestH\x00\x42\t\n\x07\x63ontent2\xb2\x03\n\x05\x41\x64min\x12\x35\n\tGetStatus\x12\x10.common.Envelope\x1a\x14.protos.ServerStatus\"\x00\x12\x37\n\x0bStartServer\x12\x10.common.Envelope\x1a\x14.protos.ServerStatus\"\x00\x12\x41\n\x11GetModuleLogLevel\x12\x10.common.Envelope\x1a\x18.protos.LogLevelResponse\"\x00\x12\x41\n\x11SetModuleLogLevel\x12\x10.common.Envelope\x1a\x18.protos.LogLevelResponse\"\x00\x12=\n\x0fRevertLogLevels\x12\x10.common.Envelope\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\nGetLogSpec\x12\x10.common.Envelope\x1a\x17.protos.LogSpecResponse\"\x00\x12\x39\n\nSetLogSpec\x12\x10.common.Envelope\x1a\x17.protos.LogSpecResponse\"\x00\x42]\n\"org.hyperledger.fabric.protos.peerB\x0c\x41\x64minPackageZ)github.com/hyperledger/fabric/protos/peerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hfc.protos.peer.admin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"org.hyperledger.fabric.protos.peerB\014AdminPackageZ)github.com/hyperledger/fabric/protos/peer'
  _globals['_SERVERSTATUS']._serialized_start=101
  _globals['_SERVERSTATUS']._serialized_end=255
  _globals['_SERVERSTATUS_STATUSCODE']._serialized_start=166
  _globals['_SERVERSTATUS_STATUSCODE']._serialized_end=255
  _globals['_LOGLEVELREQUEST']._serialized_start=257
  _globals['_LOGLEVELREQUEST']._serialized_end=313
  _globals['_LOGLEVELRESPONSE']._serialized_start=315
  _globals['_LOGLEVELRESPONSE']._serialized_end=372
  _globals['_LOGSPECREQUEST']._serialized_start=374
  _globals['_LOGSPECREQUEST']._serialized_end=408
  _globals['_LOGSPECRESPONSE']._serialized_start=410
  _globals['_LOGSPECRESPONSE']._serialized_end=460
  _globals['_ADMINOPERATION']._serialized_start=462
  _globals['_ADMINOPERATION']._serialized_end=578
  _globals['_ADMIN']._serialized_start=581
  _globals['_ADMIN']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
