# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/fabric_block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peer/fabric_block.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x17peer/fabric_block.proto\x12\x06protos\"9\n\x06\x42lock2\x12\x19\n\x11PreviousBlockHash\x18\x01 \x01(\x0c\x12\x14\n\x0cTransactions\x18\x02 \x03(\x0c\x42+Z)github.com/hyperledger/fabric/protos/peerb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BLOCK2 = _descriptor.Descriptor(
  name='Block2',
  full_name='protos.Block2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PreviousBlockHash', full_name='protos.Block2.PreviousBlockHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Transactions', full_name='protos.Block2.Transactions', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['Block2'] = _BLOCK2

Block2 = _reflection.GeneratedProtocolMessageType('Block2', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK2,
  __module__ = 'peer.fabric_block_pb2'
  # @@protoc_insertion_point(class_scope:protos.Block2)
  ))
_sym_db.RegisterMessage(Block2)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z)github.com/hyperledger/fabric/protos/peer'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
