# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hfc/protos/peer/fabric_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hfc.protos.peer import fabric_proposal_pb2 as hfc_dot_protos_dot_peer_dot_fabric__proposal__pb2
from hfc.protos.peer import fabric_proposal_response_pb2 as hfc_dot_protos_dot_peer_dot_fabric__proposal__response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hfc/protos/peer/fabric_service.proto',
  package='hfc.protos.peer',
  syntax='proto3',
  serialized_pb=_b('\n$hfc/protos/peer/fabric_service.proto\x12\x0fhfc.protos.peer\x1a%hfc/protos/peer/fabric_proposal.proto\x1a.hfc/protos/peer/fabric_proposal_response.proto2c\n\x08\x45ndorser\x12W\n\x0fProcessProposal\x12\x1f.hfc.protos.peer.SignedProposal\x1a!.hfc.protos.peer.ProposalResponse\"\x00\x42+Z)github.com/hyperledger/fabric/protos/peerb\x06proto3')
  ,
  dependencies=[hfc_dot_protos_dot_peer_dot_fabric__proposal__pb2.DESCRIPTOR,hfc_dot_protos_dot_peer_dot_fabric__proposal__response__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z)github.com/hyperledger/fabric/protos/peer'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class EndorserStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.ProcessProposal = channel.unary_unary(
          '/hfc.protos.peer.Endorser/ProcessProposal',
          request_serializer=hfc_dot_protos_dot_peer_dot_fabric__proposal__pb2.SignedProposal.SerializeToString,
          response_deserializer=hfc_dot_protos_dot_peer_dot_fabric__proposal__response__pb2.ProposalResponse.FromString,
          )


  class EndorserServicer(object):

    def ProcessProposal(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_EndorserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ProcessProposal': grpc.unary_unary_rpc_method_handler(
            servicer.ProcessProposal,
            request_deserializer=hfc_dot_protos_dot_peer_dot_fabric__proposal__pb2.SignedProposal.FromString,
            response_serializer=hfc_dot_protos_dot_peer_dot_fabric__proposal__response__pb2.ProposalResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'hfc.protos.peer.Endorser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaEndorserServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ProcessProposal(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaEndorserStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ProcessProposal(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    ProcessProposal.future = None


  def beta_create_Endorser_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('hfc.protos.peer.Endorser', 'ProcessProposal'): hfc_dot_protos_dot_peer_dot_fabric__proposal__pb2.SignedProposal.FromString,
    }
    response_serializers = {
      ('hfc.protos.peer.Endorser', 'ProcessProposal'): hfc_dot_protos_dot_peer_dot_fabric__proposal__response__pb2.ProposalResponse.SerializeToString,
    }
    method_implementations = {
      ('hfc.protos.peer.Endorser', 'ProcessProposal'): face_utilities.unary_unary_inline(servicer.ProcessProposal),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Endorser_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('hfc.protos.peer.Endorser', 'ProcessProposal'): hfc_dot_protos_dot_peer_dot_fabric__proposal__pb2.SignedProposal.SerializeToString,
    }
    response_deserializers = {
      ('hfc.protos.peer.Endorser', 'ProcessProposal'): hfc_dot_protos_dot_peer_dot_fabric__proposal__response__pb2.ProposalResponse.FromString,
    }
    cardinalities = {
      'ProcessProposal': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'hfc.protos.peer.Endorser', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
