# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hfc/protos/common/configtx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hfc.protos.common import common_pb2 as hfc_dot_protos_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hfc/protos/common/configtx.proto',
  package='hfc.protos.common',
  syntax='proto3',
  serialized_pb=_b('\n hfc/protos/common/configtx.proto\x12\x11hfc.protos.common\x1a\x1ehfc/protos/common/common.proto\"f\n\x15\x43onfigurationEnvelope\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\x0c\x12=\n\nsignatures\x18\x02 \x03(\x0b\x32).hfc.protos.common.ConfigurationSignature\"L\n\x15\x43onfigurationTemplate\x12\x33\n\x05Items\x18\x01 \x03(\x0b\x32$.hfc.protos.common.ConfigurationItem\"m\n\x06\x43onfig\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.hfc.protos.common.ChainHeader\x12\x33\n\x05items\x18\x02 \x03(\x0b\x32$.hfc.protos.common.ConfigurationItem\"\xf3\x01\n\x11\x43onfigurationItem\x12\x44\n\x04Type\x18\x01 \x01(\x0e\x32\x36.hfc.protos.common.ConfigurationItem.ConfigurationType\x12\x14\n\x0cLastModified\x18\x02 \x01(\x04\x12\x1a\n\x12ModificationPolicy\x18\x03 \x01(\t\x12\x0b\n\x03Key\x18\x04 \x01(\t\x12\r\n\x05Value\x18\x05 \x01(\x0c\"J\n\x11\x43onfigurationType\x12\n\n\x06Policy\x10\x00\x12\t\n\x05\x43hain\x10\x01\x12\x0b\n\x07Orderer\x10\x02\x12\x08\n\x04Peer\x10\x03\x12\x07\n\x03MSP\x10\x04\"E\n\x16\x43onfigurationSignature\x12\x18\n\x10signature_header\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x42-Z+github.com/hyperledger/fabric/protos/commonb\x06proto3')
  ,
  dependencies=[hfc_dot_protos_dot_common_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONFIGURATIONITEM_CONFIGURATIONTYPE = _descriptor.EnumDescriptor(
  name='ConfigurationType',
  full_name='hfc.protos.common.ConfigurationItem.ConfigurationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Policy', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Chain', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Orderer', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Peer', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSP', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=550,
  serialized_end=624,
)
_sym_db.RegisterEnumDescriptor(_CONFIGURATIONITEM_CONFIGURATIONTYPE)


_CONFIGURATIONENVELOPE = _descriptor.Descriptor(
  name='ConfigurationEnvelope',
  full_name='hfc.protos.common.ConfigurationEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='hfc.protos.common.ConfigurationEnvelope.config', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signatures', full_name='hfc.protos.common.ConfigurationEnvelope.signatures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=189,
)


_CONFIGURATIONTEMPLATE = _descriptor.Descriptor(
  name='ConfigurationTemplate',
  full_name='hfc.protos.common.ConfigurationTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Items', full_name='hfc.protos.common.ConfigurationTemplate.Items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=267,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='hfc.protos.common.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='hfc.protos.common.Config.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='hfc.protos.common.Config.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=378,
)


_CONFIGURATIONITEM = _descriptor.Descriptor(
  name='ConfigurationItem',
  full_name='hfc.protos.common.ConfigurationItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='hfc.protos.common.ConfigurationItem.Type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastModified', full_name='hfc.protos.common.ConfigurationItem.LastModified', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ModificationPolicy', full_name='hfc.protos.common.ConfigurationItem.ModificationPolicy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Key', full_name='hfc.protos.common.ConfigurationItem.Key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='hfc.protos.common.ConfigurationItem.Value', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGURATIONITEM_CONFIGURATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=624,
)


_CONFIGURATIONSIGNATURE = _descriptor.Descriptor(
  name='ConfigurationSignature',
  full_name='hfc.protos.common.ConfigurationSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature_header', full_name='hfc.protos.common.ConfigurationSignature.signature_header', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='hfc.protos.common.ConfigurationSignature.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=695,
)

_CONFIGURATIONENVELOPE.fields_by_name['signatures'].message_type = _CONFIGURATIONSIGNATURE
_CONFIGURATIONTEMPLATE.fields_by_name['Items'].message_type = _CONFIGURATIONITEM
_CONFIG.fields_by_name['header'].message_type = hfc_dot_protos_dot_common_dot_common__pb2._CHAINHEADER
_CONFIG.fields_by_name['items'].message_type = _CONFIGURATIONITEM
_CONFIGURATIONITEM.fields_by_name['Type'].enum_type = _CONFIGURATIONITEM_CONFIGURATIONTYPE
_CONFIGURATIONITEM_CONFIGURATIONTYPE.containing_type = _CONFIGURATIONITEM
DESCRIPTOR.message_types_by_name['ConfigurationEnvelope'] = _CONFIGURATIONENVELOPE
DESCRIPTOR.message_types_by_name['ConfigurationTemplate'] = _CONFIGURATIONTEMPLATE
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['ConfigurationItem'] = _CONFIGURATIONITEM
DESCRIPTOR.message_types_by_name['ConfigurationSignature'] = _CONFIGURATIONSIGNATURE

ConfigurationEnvelope = _reflection.GeneratedProtocolMessageType('ConfigurationEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONENVELOPE,
  __module__ = 'hfc.protos.common.configtx_pb2'
  # @@protoc_insertion_point(class_scope:hfc.protos.common.ConfigurationEnvelope)
  ))
_sym_db.RegisterMessage(ConfigurationEnvelope)

ConfigurationTemplate = _reflection.GeneratedProtocolMessageType('ConfigurationTemplate', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONTEMPLATE,
  __module__ = 'hfc.protos.common.configtx_pb2'
  # @@protoc_insertion_point(class_scope:hfc.protos.common.ConfigurationTemplate)
  ))
_sym_db.RegisterMessage(ConfigurationTemplate)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'hfc.protos.common.configtx_pb2'
  # @@protoc_insertion_point(class_scope:hfc.protos.common.Config)
  ))
_sym_db.RegisterMessage(Config)

ConfigurationItem = _reflection.GeneratedProtocolMessageType('ConfigurationItem', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONITEM,
  __module__ = 'hfc.protos.common.configtx_pb2'
  # @@protoc_insertion_point(class_scope:hfc.protos.common.ConfigurationItem)
  ))
_sym_db.RegisterMessage(ConfigurationItem)

ConfigurationSignature = _reflection.GeneratedProtocolMessageType('ConfigurationSignature', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONSIGNATURE,
  __module__ = 'hfc.protos.common.configtx_pb2'
  # @@protoc_insertion_point(class_scope:hfc.protos.common.ConfigurationSignature)
  ))
_sym_db.RegisterMessage(ConfigurationSignature)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z+github.com/hyperledger/fabric/protos/common'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
