# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hfc/protos/common/ledger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hfc/protos/common/ledger.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ehfc/protos/common/ledger.proto\x12\x06\x63ommon\"\x9d\x01\n\x0e\x42lockchainInfo\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x18\n\x10\x63urrentBlockHash\x18\x02 \x01(\x0c\x12\x19\n\x11previousBlockHash\x18\x03 \x01(\x0c\x12\x46\n\x1b\x62ootstrapping_snapshot_info\x18\x04 \x01(\x0b\x32!.common.BootstrappingSnapshotInfo\";\n\x19\x42ootstrappingSnapshotInfo\x12\x1e\n\x16last_block_in_snapshot\x18\x01 \x01(\x04\x42V\n$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/commonb\x06proto3'
)




_BLOCKCHAININFO = _descriptor.Descriptor(
  name='BlockchainInfo',
  full_name='common.BlockchainInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='common.BlockchainInfo.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentBlockHash', full_name='common.BlockchainInfo.currentBlockHash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previousBlockHash', full_name='common.BlockchainInfo.previousBlockHash', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bootstrapping_snapshot_info', full_name='common.BlockchainInfo.bootstrapping_snapshot_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=200,
)


_BOOTSTRAPPINGSNAPSHOTINFO = _descriptor.Descriptor(
  name='BootstrappingSnapshotInfo',
  full_name='common.BootstrappingSnapshotInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_block_in_snapshot', full_name='common.BootstrappingSnapshotInfo.last_block_in_snapshot', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=261,
)

_BLOCKCHAININFO.fields_by_name['bootstrapping_snapshot_info'].message_type = _BOOTSTRAPPINGSNAPSHOTINFO
DESCRIPTOR.message_types_by_name['BlockchainInfo'] = _BLOCKCHAININFO
DESCRIPTOR.message_types_by_name['BootstrappingSnapshotInfo'] = _BOOTSTRAPPINGSNAPSHOTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockchainInfo = _reflection.GeneratedProtocolMessageType('BlockchainInfo', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKCHAININFO,
  '__module__' : 'hfc.protos.common.ledger_pb2'
  # @@protoc_insertion_point(class_scope:common.BlockchainInfo)
  })
_sym_db.RegisterMessage(BlockchainInfo)

BootstrappingSnapshotInfo = _reflection.GeneratedProtocolMessageType('BootstrappingSnapshotInfo', (_message.Message,), {
  'DESCRIPTOR' : _BOOTSTRAPPINGSNAPSHOTINFO,
  '__module__' : 'hfc.protos.common.ledger_pb2'
  # @@protoc_insertion_point(class_scope:common.BootstrappingSnapshotInfo)
  })
_sym_db.RegisterMessage(BootstrappingSnapshotInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
