# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hfc/protos/common/ledger.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ehfc/protos/common/ledger.proto\x12\x06\x63ommon\"\x9d\x01\n\x0e\x42lockchainInfo\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x18\n\x10\x63urrentBlockHash\x18\x02 \x01(\x0c\x12\x19\n\x11previousBlockHash\x18\x03 \x01(\x0c\x12\x46\n\x1b\x62ootstrapping_snapshot_info\x18\x04 \x01(\x0b\x32!.common.BootstrappingSnapshotInfo\";\n\x19\x42ootstrappingSnapshotInfo\x12\x1e\n\x16last_block_in_snapshot\x18\x01 \x01(\x04\x42V\n$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hfc.protos.common.ledger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$org.hyperledger.fabric.protos.commonZ.github.com/hyperledger/fabric-protos-go/common'
  _globals['_BLOCKCHAININFO']._serialized_start=43
  _globals['_BLOCKCHAININFO']._serialized_end=200
  _globals['_BOOTSTRAPPINGSNAPSHOTINFO']._serialized_start=202
  _globals['_BOOTSTRAPPINGSNAPSHOTINFO']._serialized_end=261
# @@protoc_insertion_point(module_scope)
