# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hfc/protos/orderer/etcdraft/metadata.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*hfc/protos/orderer/etcdraft/metadata.proto\x12\x08\x65tcdraft\"U\n\rBlockMetadata\x12\x15\n\rconsenter_ids\x18\x01 \x03(\x04\x12\x19\n\x11next_consenter_id\x18\x02 \x01(\x04\x12\x12\n\nraft_index\x18\x03 \x01(\x04\"\'\n\x0f\x43lusterMetadata\x12\x14\n\x0c\x61\x63tive_nodes\x18\x01 \x03(\x04\x42j\n.org.hyperledger.fabric.protos.orderer.etcdraftZ8github.com/hyperledger/fabric-protos-go/orderer/etcdraftb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hfc.protos.orderer.etcdraft.metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.org.hyperledger.fabric.protos.orderer.etcdraftZ8github.com/hyperledger/fabric-protos-go/orderer/etcdraft'
  _globals['_BLOCKMETADATA']._serialized_start=56
  _globals['_BLOCKMETADATA']._serialized_end=141
  _globals['_CLUSTERMETADATA']._serialized_start=143
  _globals['_CLUSTERMETADATA']._serialized_end=182
# @@protoc_insertion_point(module_scope)
