# Copyright the Hyperledger Fabric Python SDK contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-18.04

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: pip install virtualenv
    displayName: Install VirtualEnv
  - script: make check
    displayName: Run Checks
