# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hfc/protos/token/expectations.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hfc.protos.token import transaction_pb2 as hfc_dot_protos_dot_token_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#hfc/protos/token/expectations.proto\x12\x05token\x1a\"hfc/protos/token/transaction.proto\"W\n\x10TokenExpectation\x12\x34\n\x11plain_expectation\x18\x01 \x01(\x0b\x32\x17.token.PlainExpectationH\x00\x42\r\n\x0b\x45xpectation\"\x97\x01\n\x10PlainExpectation\x12:\n\x12import_expectation\x18\x01 \x01(\x0b\x32\x1c.token.PlainTokenExpectationH\x00\x12<\n\x14transfer_expectation\x18\x02 \x01(\x0b\x32\x1c.token.PlainTokenExpectationH\x00\x42\t\n\x07payload\"<\n\x15PlainTokenExpectation\x12#\n\x07outputs\x18\x01 \x03(\x0b\x32\x12.token.PlainOutputBQ\n#org.hyperledger.fabric.protos.tokenZ*github.com/hyperledger/fabric/protos/tokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hfc.protos.token.expectations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#org.hyperledger.fabric.protos.tokenZ*github.com/hyperledger/fabric/protos/token'
  _globals['_TOKENEXPECTATION']._serialized_start=82
  _globals['_TOKENEXPECTATION']._serialized_end=169
  _globals['_PLAINEXPECTATION']._serialized_start=172
  _globals['_PLAINEXPECTATION']._serialized_end=323
  _globals['_PLAINTOKENEXPECTATION']._serialized_start=325
  _globals['_PLAINTOKENEXPECTATION']._serialized_end=385
# @@protoc_insertion_point(module_scope)
